---
title: "R Notebook"
output: html_notebook
---
```{r}
require(kknn)
library(kknn)

data <- read.csv("TelcoCustomerChurn.csv")
str(data)

cost_matrix <- matrix(c(1,-1,-2,1), nrow = 2)
cost_matrix

measure <- function(cm){
  return(cm*cost_matrix)
}
```

Tiền xử lý dữ liệu
```{r}
row <- nrow(data)
train_index <- sample(1:row, size = trunc(0.8 * row))
train_set <- data[train_index,]
test_set <- data[-train_index,]
train_row <- nrow(train_set)
#Chia tập dữ liệu train thành 8 phần
nfolds <- 8 # số fold
ids <- 1:train_row #tạo id từ 1 tới số dòng tập train
index <- sample(ids) # xao tron ngau nhien ids
fold <- rep(1:nfolds, each = train_row/nfolds, len = 5634) # Tạo mảng từ 1 tới 8, coppy mỗi phần từ bằng số dòng dữ liệu của mỗi folds, được mảng dài bằng số lượng index
folds <- split(index, fold) # tao mot danh sach voi cac index cho moi fold
data <- train_set
data$Churn <- as.character(data$Churn)
data$Churn <- as.factor(data$Churn)
ks <- c(1:100)
accs <- matrix(0, nrow = length(ks), ncol = nfolds + 1)
result <- matrix(0, nrow = length(ks), ncol = nfolds + 2)
length(fold)
length(index)
```
Huấn luyện mô hình

```{r}
set.seed(1111)
for (k in ks) {
  s = 0
  for (i in 1:nfolds) {
      t <- kknn(Churn ~ -customerID,
        train = data[-folds[[i]], ],
        test = data[folds[[i]], ],
        k = k,
        distance = 2,
        kernel = "gaussian")
    Churn.Fitted <- fitted(t)
    confusion <- table(Churn.Fitted,data[folds[[i]],"Churn"])
    confusion_cost <- measure(confusion)
    a <- sum(confusion_cost)/length(folds[[i]])
    s = s + a
    accs[k, i] = a
    result[k, i] = a
  }
  result[k, nfolds + 1] = k
  accs[k, nfolds + 1] = s / nfolds
  result[k, nfolds + 2] = s / nfolds
}
rownames(accs) <- paste ("k = ", ks, sep = "")
colnames(accs) <- c(paste("fold ", 1:nfolds, sep = ""), "average")
rownames(result) <- paste ("k = ", ks, sep = "")
colnames(result) <- c(paste("fold ", 1:nfolds, sep = ""),"k", "average")
accs
```
Đồ thị kết quả theo k
```{r}
library(ggplot2)
data <- data.frame(k = ks, r = as.numeric(accs[, nfolds + 1]))
ggplot(data = data, mapping = aes(x = k, y = r)) +
theme_light() +
ggtitle("Average accuracy by k-fold cross validation") +
xlab("k") +
ylab("Accuracy") +
geom_point(colour = "red", size = 4, shape = 21, fill = "white") +
geom_line(colour = "red", linetype = "dashed", fill = "white")
```

Đồ thị kết quả theo k
```{r}
# Tìm giá trị k tốt nhất
result_df <- as.data.frame(result)
get_max <- result_df[which(result_df$average == max(result_df$average)),]
k_fit = get_max$k
## Đánh giá mô hình
data = read.csv("TelcoCustomerChurn.csv")
data$Churn <- as.character(data$Churn)
data$Churn <- as.factor(data$Churn)
m = nrow(data)
train = sample(m,size = trunc(0.8 * m))
trainSet = data[train,]
testSet = data[-train,]
t <- kknn(Churn ~ -customerID, trainSet,testSet, k=70  , distance = 2, kernel = "gaussian")
fit <- fitted(t)
confusion <- table(fit,testSet$Churn)
confusion_cost <- measure(confusion)
res <- sum(confusion_cost)/nrow(testSet)
res
```

